### ISSUE TITLE
Favicons

### ISSUE THREAD

**Issue by halfempty** [everythingtype/jsa#1]
Traditional first issue!

**Comment by halfempty** [comment]
Done

**Comment by gehalber** [comment]
We might want to tweak it. I'm going to reopen to reevaluate this week

**Comment by halfempty** [comment]
I tweaked these at the smallest sizes (the ones that appear in tabs). I replaced the too-small-to-really-work JSA logo with one of the mesh patterns @KyleETC's been working on. 

The logo remains in larger contexts (Safari bookmarks, etc).
