### ISSUE TITLE
Home Page Carousel

### ISSUE THREAD

**Issue by devinsays** [everythingtype/jsa#10]
I set up a carousel for the home page using the flickity (http://flickity.metafizzy.co/) library as suggested by @halfempty- which was a really nice and quick integration.

You can see it live on the site now:
http://jsa.etc-nyc.com

Example screenshot:
![example](https://cloud.githubusercontent.com/assets/431879/7212291/12b8a8fa-e52a-11e4-965a-b6cc2d3a8e17.png)

Design
---

The design mock called for a full bleed image, but flickity has this nice option for an infinite carousel with images on either side- so I wanted to run that option by you @gehalber. It makes it so the image height doesn't have to be so tall on large images, and might also encourage more interaction as other slides are visible. Let me know if you have any thoughts on this.

Functionality
---

@halfempty I currently have this set up to query all the project taxonomies and then display the first image from the most recent project of each- but I'll switch this shortly to the ACF setup you have.

**Comment by gehalber** [comment]
After taking a close look, I think we really need to go full screen with the images. We lose the clean impact of single images without it. Hopefully flickity can accomplish this too.

**Comment by devinsays** [comment]
@gehalber Yep, no problem. I'll make the update.

**Comment by halfempty** [comment]
This is a duplicate, now. Closing.
