### ISSUE TITLE
Responsive: Read more/less

### ISSUE THREAD

**Issue by halfempty** [everythingtype/jsa#100]
> read more/less error - not sure if this is because of a back-end issue (code or wordpress), but needs to be fixed. we also need to make sure that the amount of text we keep before the "break" works well for both desktop and responsive. for example, here you can see that the description is so long that data runs off the bottom, which isn't good. although it may look fine on desktop.

> lets fix

**Comment by halfempty** [comment]
@gehalber I'm not reproducing this bug. Are you? Could it have just been a one-time glitch?

**Comment by gehalber** [comment]
I’m not seeing it on either chrome or safari…

We should do a redirect for the url: joelsandersarchitect.com/mobile/

Which was the url linking from safari search.

**Comment by halfempty** [comment]
@gehalber Okay, closing this
