### ISSUE TITLE
Removing the project order number in the sidebar

### ISSUE THREAD

**Issue by gehalber** [everythingtype/jsa#108]
Is it easy to remove this, especially because it doesn't have any function now? Pesky request, I know.

**Comment by halfempty** [comment]
@gehalber Remind me what this is? Screenshot?

**Comment by gehalber** [comment]
Attributes: Order

**Comment by halfempty** [comment]
@gehalber On the Edit screen? That box is standard with WP, it's not something I added and so not something I can easily remove.

**Comment by gehalber** [comment]
Ok. That’s all I needed to hear. Thanks.
