### ISSUE TITLE
Responsive: Homepage triptych images above the fold

### ISSUE THREAD

**Issue by gehalber** [everythingtype/jsa#109]
1. Is it possible for these images to respond to the height of the browser so they're always above the fold

or

2. we might need to shorten the height of these

What do you think?

**Comment by halfempty** [comment]
@gehalber I would advise against this because it opens a can of worms. For instance, remember that phones can be turned sideways, in which the vertical is very short. Consider also the incredible diversity of screen sizes / shapes, especially in the Android ecosystem.

**Comment by gehalber** [comment]
Yeah, I totally understand that. I wonder if we can meet them in the middle, by simple decreasing the height of the tripdych images? Would that be easy to do?

**Comment by halfempty** [comment]
**@gehalber says:**

![image](https://cloud.githubusercontent.com/assets/775543/14624048/98011ef0-059c-11e6-8ae9-1685e388a9f7.png)

I wanted to get your thoughts on this. Will this be simple enough to do?

Mobile Homepage:
Change proportions of the images to be: 
375px x 159px

3px in between each image.

Also total header height is changed to: 75px on mobile.

Attaching screen shot for you.

Don’t do this work yet. I need to get approval on this. But just let me know if this is a simple fix.

**Comment by gehalber** [comment]
If you could get back to me on this tonight, that'd be great!

**Comment by halfempty** [comment]
@gehalber Yes, we can make this work. 

Will you want to use images at the smaller size that are cropped substantially differently than at the larger? I ask 'cause it looks like the institutional one is cropped to a detail compared to what we're doing now. If yes, that'll add complication.

**Comment by gehalber** [comment]
Are you asking if I want to change proportion/cropping between desktop and mobiles? Maybe. Is it better if we change the crop of the image in media library?

**Comment by halfempty** [comment]
@gehalber Not exactly. I'm asking about what's known as the "art direction use case". This is where an image that is substantially visually different is used at the smaller size. Do you want to specify a different image at mobile than desktop?

**Comment by gehalber** [comment]
No. Let’s just use the same image.

**Comment by gehalber** [comment]
Also we got approval from JSA to go ahead with this. So if you could please implement. Thanks!

**Comment by halfempty** [comment]
@gehalber Okay, these tweaks are in:

http://dev.joelsandersarchitect.com/home/

I notice the carousel label text is in the comp at 30.467 pt. On the site I have it as 26, and that persists to desktop view as well. Would you like that bumped up? Or fine as is?

**Comment by gehalber** [comment]
Nice looking. This is great.
