### ISSUE TITLE
Dot Overlays

### ISSUE THREAD

**Issue by devinsays** [everythingtype/jsa#11]
The dot overlays provided are really neat! I implemented one of them for the home page (hover over a project) http://jsa.etc-nyc.com. Let me know how you feel about transition speed, etc.

However, none of the patterns lined up perfectly. The one I used was close, but you can see a line where the dots don't quite align on the left side of the pattern. @gehalber Could you create a new one where the pattern can repeat seamlessly?

If you create this a png, we'd need a 2x version as well for retina. Or, a properly sized SVG would also work.

**Comment by gehalber** [comment]
Cool! This is looking really nice, but totally agree we need it seamlessly. @halfempty has already made some progress on this aspect of the project. Perhaps he could hook you up with the latest iteration of the dots for now.
