### ISSUE TITLE
Responsive: related projects

### ISSUE THREAD

**Issue by gehalber** [everythingtype/jsa#115]
Can we remove the third project on the mobile phone so there are only two showing and we don't get the awkward space on the second row in mobile

**Comment by halfempty** [comment]
@gehalber The philosophy of responsive is that we're offering the same content regardless of screen size. What do you think, in this case?

**Comment by gehalber** [comment]
I agree, but in some ways I feel that this content is superfluous. It functions more to get the user clicking to another project so losing the third project doesn't matter. 

Let's do this.

**Comment by halfempty** [comment]
Done
