### ISSUE TITLE
Responsive: Homepage

### ISSUE THREAD

**Issue by gehalber** [everythingtype/jsa#116]
From JSA:
Also, the homepage seems to "stick" while loading, preventing users from scrolling down. I understand that a pause for loading might be necessary, but it feels a little awkward. Can you recommend a way of making this feel more seamless? Perhaps a splash screen like on the desktop?

**Comment by halfempty** [comment]
@gehalber This doesn't have to do with loading. It's a bug-- it thinks the splash screen is visible, even though it's not. I'll work on a fix...

**Comment by halfempty** [comment]
Fixed
