### ISSUE TITLE
Selected Text has Different Color

### ISSUE THREAD

**Issue by halfempty** [everythingtype/jsa#119]

**Comment by halfempty** [comment]
@gehalber In fact, we were already defining highlight colors. They're in as black highlight with white text. Is this what he's objecting to? Would you like me to change this in some way?

**Comment by gehalber** [comment]
Here’s the image from Safari, I think. Its working properly in Chrome. 
Not sure what the issue is.

**Comment by halfempty** [comment]
@gehalber The image didn't come through. Please repost? For me it appears to be working in Safari.

**Comment by gehalber** [comment]
Just confirming, that its blue in Safari. See pic:

<img width="1071" alt="screen shot 2016-04-13 at 10 58 42 pm" src="https://cloud.githubusercontent.com/assets/6076488/14515825/53661392-01cb-11e6-9f62-65d9bd6d7e2d.png">

**Comment by halfempty** [comment]
@gehalber Oh, I get it now! Non-paragraphs are different. Ok, I've made that rule more general.
