### ISSUE TITLE
GIFs

### ISSUE THREAD

**Issue by halfempty** [everythingtype/jsa#121]

**Comment by halfempty** [comment]
@gehalber Okay, GIFs!

It is possible to add GIFs to the project page. Here's an example where I've added a GIF to the description image and also to the final slide on the page:

http://dev.joelsandersarchitect.com/project/jewish-museum/

**Comment by gehalber** [comment]
Great!
Let’s push this.

**Comment by halfempty** [comment]
@gehalber GIFs are available on live

**Comment by halfempty** [comment]
@gehalber Ps. To clarify, I haven't actually added the GIFs to their corresponding projects. But the functionality is there.

**Comment by gehalber** [comment]
Sorry, reopening this.
The click to next slide doesn't work for these GIFs

**Comment by gehalber** [comment]
OOOPs my bad. It does! Please disregard.
