### ISSUE TITLE
Field tinkering

### ISSUE THREAD

**Issue by halfempty** [everythingtype/jsa#122]
> I think I may have done some minor damage to the CMS settings for "Project Details." Check out the data list for Kunshan HERE. You'll see it lists "size" twice. I added a few new fields to the Project Details settings (with, associate, mep, structural, etc.) and then I noticed this happening. After we resolve the video issue, can you or Marty help me sort this out? Sorry for tinkering!

http://joelsandersarchitect.com/project/kunshan-phoenix-cultural-mall/

**Comment by halfempty** [comment]
@gehalber I think maybe he fixed it himself? I don't see the problem

**Comment by gehalber** [comment]
Looks like “Size” is listed twice?
That’s what I see.

**Comment by halfempty** [comment]
@gehalber Ah, now I see! Yeah-- he's not supposed to be tinkering there. It's possible to do serious damage to the site with an errant click! Non-recoverable damage. Ask him to please keep out of that area.

He's added a bunch of new left-side labels to the description. I can program for each of those.

However, an aspect that you might want to weigh-in on is that some of them are longer than what our design expects. He's got:

Year
Architect
Associate Architect
With
Landscape Architect
Structural Engineer
MEP Engineer
Photos
Location
Size
Scope

**Comment by gehalber** [comment]
Ok. We might need to move the second column over a bit to give these some more space.
Is there a way he can add these, or is that a no no?

**Comment by halfempty** [comment]
@gehalber We can make it so there are no pre-defined options. He will then specify whatever he likes, on each side. 

This will require a new / different field format. If we do this he'll have to re-enter this info for all projects.

**Comment by gehalber** [comment]
Ok. I’ll ask him.

Will you go ahead and push the homepage change live?

**Comment by gehalber** [comment]
Ok. They're ok with re-entering all project info so they can customize. Can you change?
While you're in there, can you move the second column further to the right in order to fit a term like "Landscape Architect" (we'll use that as the worst case scenario).

**Comment by halfempty** [comment]
Done!
