### ISSUE TITLE
Private projects on Projects page

### ISSUE THREAD

**Issue by halfempty** [everythingtype/jsa#123]
> Urgent Item! The private projects are showing up on the site. I just deleted them - but the thumbnail rectangles are still showing up on the projects page. Help!

**Comment by halfempty** [comment]
@gehalber So, I believe I can do something about this. I can check if they're "published" before showing the thumbnail. Should I?

**Comment by gehalber** [comment]
Sure

**Comment by halfempty** [comment]
@gehalber okay this is done and applied to the live site
