### ISSUE TITLE
Google Analytics

### ISSUE THREAD

**Issue by halfempty** [everythingtype/jsa#124]
@gehalber Google Analytics isn’t setup on the site right now. I don't have a JSA entry in my Google Analytics account. Do you have it on yours? Do they have an account?

**Comment by gehalber** [comment]
Here's the code:
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-65857323-1', 'auto');
  ga('send', 'pageview');

</script>

**Comment by gehalber** [comment]
Sending you an email with this...
