### ISSUE TITLE
Email Signup form

### ISSUE THREAD

**Issue by halfempty** [everythingtype/jsa#128]
![image](https://user-images.githubusercontent.com/775543/32009037-7c85ccb6-b973-11e7-823d-beaee6b99162.png)

**Comment by halfempty** [comment]
@keningzhu @gehalber Is Catherine still the contact at JSA? Should I email her re: MailChimp info?

**Comment by gehalber** [comment]
@halfempty 
I don't think so. You can email Josh though. Lmk if you need his email.

**Comment by halfempty** [comment]
@gehalber @keningzhu I think I have this working. Will you take a look?

http://joelsandersarchitect.com/contact/

**Comment by gehalber** [comment]
@halfempty
Looks good! Make the button not have rounded corners?
Let me know about the other items on their list when you can.

g

**Comment by halfempty** [comment]
@gehalber Okay, this is fixed on Mobile Safari now
