### ISSUE TITLE
Homepage Carousel

### ISSUE THREAD

**Issue by gehalber** [everythingtype/jsa#129]
@halfempty 
We want to change the heading "Living and Working" to "Arts". When we try to change the "heading name" it does not activate the new label on the home front page of the website. (Please see PDF "Home Page Heading"). This might be something we're not supposed to change on the back-end? Regardless, I thought Marty had set up the site so that we could change the text of the 3 feature categories ("Residential" Institutional" and "Public Space") to something else. JD note: I haven't been directly involved in these recent edits, so I'm not even sure how "Living & Working" (a research category) became an option for the homepage carousel, which I thought was limited to just project categories. In short, we want to be able to control the text of the 3 carousel categories along with the URL that brings users to a specific page on the site if they click a carousel image. You'll also notice that clicking the "living and working" image brings you to a 404-error page - so the URL functionality apparently needs to be tweaked.

**Comment by halfempty** [comment]
@gehalber Geoff, do you know what they're saying here? I can't find "Living and Working" anywhere on the page

**Comment by halfempty** [comment]
@gehalber I found a reference to "Living and Working" in the code, seemingly from an earlier phase of the project... it shouldn't have been coming up, but maybe it somehow was? So I've removed it.
