### ISSUE TITLE
Carousel Starting image

### ISSUE THREAD

**Issue by gehalber** [everythingtype/jsa#131]
@halfempty 
When the carousel starts beneath the JSA logo mask, it always starts randomly with either institutional or residential, but never the 3rd category. Is there a reason for this? Can it be easily changed so that the carousel start is always random?

**Comment by halfempty** [comment]
@gehalber It seems their question has an inaccurate premise. There is no randomization of the slides. If they're seeing Residential, I suspect it's simply because the slideshow has already advanced to the second slide.

Should we randomize the order of the slides?

**Comment by halfempty** [comment]
@gehalber Okay, these have now been randomized.
