### ISSUE TITLE
Carousel labels

### ISSUE THREAD

**Issue by halfempty** [everythingtype/jsa#132]
> Currently Public Space, or Living and Working - which we're trying to change to "Arts"

**Comment by halfempty** [comment]
@gehalber Are they asking here to have "Public Space" switched to "Arts"?

**Comment by gehalber** [comment]
@halfempty 
Is that something that we need to do, or is it something they can do in the future?

**Comment by gehalber** [comment]
@halfempty 
Yes, change Public Space to Arts in the carousel.

**Comment by halfempty** [comment]
Done

**Comment by gehalber** [comment]
@halfempty 
Is this something JSA can do in the future by themselves, or no?

**Comment by halfempty** [comment]
@gehalber No... If they'd like to do that I can redevelop it. But as it is, the names are hard-coded.

**Comment by gehalber** [comment]
@halfempty Ok. Thanks!
