### ISSUE TITLE
Splash Page

### ISSUE THREAD

**Issue by halfempty** [everythingtype/jsa#14]
- See through
- Fade Away

**Comment by halfempty** [comment]
@gehalber Made some progress on this. Please take a look.

**Comment by halfempty** [comment]
@gehalber Do you want the same effect we're doing for the ETC splash page for this JSA splash? That is, should it be possible to return to the homepage without triggering the splash screen?

**Comment by gehalber** [comment]
Yes. That would be great.
Thanks.

**Comment by halfempty** [comment]
@gehalber Okay, that's in.

When you get a chance, please let me know how the splash page is feeling to you, overall.

Thanks!

**Comment by gehalber** [comment]
I like that you have to click into the page actually, and I tend to think we should keep it this way, but just so I know, can you also time it so it fades out after say 5 seconds or so?

**Comment by halfempty** [comment]
@gehalber Yes, we could also put a timer on it.

**Comment by gehalber** [comment]
cool.

**Comment by halfempty** [comment]
@gehalber There's sometimes a bit of a flash of the content under the splash, as the page is loading. It's something I need to work a bit on.

**Comment by gehalber** [comment]
Slow down the dissolve affect once you click.

Do you think we should add a button to this page to make sure users get it? Ala...

![screen shot 2015-06-05 at 12 49 26 pm](https://cloud.githubusercontent.com/assets/6076488/8010783/53fd7624-0b81-11e5-9ca4-9172e8ea7ffb.png)

**Comment by halfempty** [comment]
@gehalber 

I've added "Read more". Not sure I got the proportions exactly correct, but it'll give you the idea. If you like it and want to keep it, could you add it to the InDesign for easy measurement?

I've also slowed the transition from 500 ms to 1000 ms. Better? Make it even slower?

**Comment by gehalber** [comment]
Oh, you can close this after you make "Read More" hover to black. Speed seems good.

**Comment by halfempty** [comment]
@gehalber Okay, done.
