### ISSUE TITLE
Header

### ISSUE THREAD

**Issue by halfempty** [everythingtype/jsa#15]
- Pin to top
- Submenus
- Remove search

**Comment by halfempty** [comment]
@gehalber

I've fixed the header. And when you scroll down a bit, the grey line fades in.

There's something about it I want to spend a bit more time on, however. On my Air, I can sometimes make the header stutter-- like it can't keep up with the scrolling, especially if other things are moving on the page.

I suspect this might have to do with the test that turns the grey line on and off, which fires continuously during scrolling. I want to take a look to see if there's a way to code this in a more RAM-efficient way.

**Comment by gehalber** [comment]
cool…

homepage is looking sick!

**Comment by halfempty** [comment]
A couple of bugs remaining in the Navigation menus:

- The main nav on the "About" section is pushing down under the secondary nav
- There's sometimes a flash at page load, as elements situate themselves

**Comment by halfempty** [comment]
I've put in something for the scrolling stutter, and it appears much better now.

**Comment by halfempty** [comment]
@gehalber The "About" nav is now on the correct line
