### ISSUE TITLE
Homepage Carousel

### ISSUE THREAD

**Issue by halfempty** [everythingtype/jsa#16]
- Two sets
- Arrows

**Comment by halfempty** [comment]
@gehalber 

I've updated the styling of this. Also, we're randomly picking between two sets of images.

Question: Should the slides click through to the corresponding project categories?

You mentioned you've got updated styles for the carousel arrows?
And also for the carousel labels?

**Comment by gehalber** [comment]
Yes, the slides should click to corresponding categories.
We’ll hook you up with those arrows this week.

**Comment by halfempty** [comment]
@gehalber Okay, arrows are in. Also, the slides click through.
