### ISSUE TITLE
Thumbnails

### ISSUE THREAD

**Issue by halfempty** [everythingtype/jsa#17]
- Course holes
- Whole-block hover
- Slap not fade

**Comment by halfempty** [comment]
@gehalber 

The mockup shows most thumbnails as landscape and cropped to the full size. But in the homepage news section there's one that's portrait, and it's scaled-down to fit in the height. And it's got a black background. 

This effect will be tricky to pull off. I have an idea for it, but it's complicated and would take a bit of time to do. (It would involve comparing the width and height of each image and outputting special code for portrait-orientation.) 

It would be much simpler to use horizontal crops for all. 

Please let me know if you think it's worth concentrating on!

**Comment by halfempty** [comment]
@gehalber 

Also, what should we do if a Project or News item has no thumbnail? Have a fallback?

**Comment by gehalber** [comment]
Every project and news should have an image, but in case one doesn’t we can come up with a placeholder. I do like the black rectangles you have in place for images that are still loading.

I’ll put it on our list of things to do.

**Comment by gehalber** [comment]
I will have them make horizontal images with black background in the case they need/want to use vertical images.
