### ISSUE TITLE
Project Page

### ISSUE THREAD

**Issue by halfempty** [everythingtype/jsa#18]
- Make like ETC
- Related Projects thumbnails
- Hide "Slideshow" feature for now

**Comment by halfempty** [comment]
@gehalber The broad-strokes of the project page are in, I think. The items that still need work are:

- The other slide types (full-bleed, side-by-side and animated). I will open new Issues for each.
- "Related Projects". I will open a new issue for this as well.

Aside from those, how's it looking to you?

**Comment by gehalber** [comment]
This is looking great too. Under the marginal info on the right side, is it possible to not show the entries that are blank? Or is that the user doing this: http://jsa.etc-nyc.com/project/easyhotel/

We may not want to show the information at the bottom of the scroll. Meaning that the only time you see it is when you click on info. What do you think?

**Comment by halfempty** [comment]
Personally, I think it's good to have the text at the bottom. I read through one of the descriptions and it really was integral to understanding the concept of the project. It'd be a shame if people were to miss them, imo.

Yeah, those dashes were put in by the user, meaning he actively chose to have them display that way.

**Comment by gehalber** [comment]
Ok. They like this as well. This is being updated a bit to include the related projects with back button to appropriate typology (on page 22 of most recent indd)
![screen shot 2015-06-05 at 1 02 14 pm](https://cloud.githubusercontent.com/assets/6076488/8011000/1c7ced90-0b83-11e5-95e7-561e627248a6.png)

**Comment by halfempty** [comment]
@gehalber Regarding the "Back to" link, two notes:

1. There's a pluralization issue. The categories have names like "Galleries," and there's no automatic way to convert that to "Gallery." So instead of saying "Back to Gallery Projects," these lables will be more like "Back to Galleries."

2. Also, the client has filed some projects in more than one category. In these cases the Back button will link to one of them. (I think it will go with whichever is first, alphabetically.)

I still need to get the custom arrow glyph in there.

**Comment by gehalber** [comment]
Ok. Great!
