### ISSUE TITLE
People Page Template

### ISSUE THREAD

**Issue by halfempty** [everythingtype/jsa#20]
- ACF blocks

**Comment by halfempty** [comment]
@gehalber The fields for the People page are in. (But not the front-end yet.)

Question about the images: They're shown here as square. Should I set-up a new crop size for this? Or should we allow any shape, but fit them into a square image box?

**Comment by gehalber** [comment]
Good question. I don’t think they have portraits yet, let’s just let them be any shape anchored to the top left corner and we’ll set manual specifications for their media.

**Comment by gehalber** [comment]
Going to close this for now.

**Comment by halfempty** [comment]
@gehalber Should this one just move over to the standard Page template?

**Comment by gehalber** [comment]
sure.

**Comment by gehalber** [comment]
Hope I didn't speak too soon. Can we change the text size of the body copy to 22px and leave the Title information as is?

**Comment by halfempty** [comment]
@gehalber To clarify-- This uses the "General Page" template. Would you like the 22px on all instances of General Page, or would you like it on just this page?

**Comment by gehalber** [comment]
Let's apply the 22px to general page template and see what that looks like.

**Comment by gehalber** [comment]
But we still need the portraits to be on the left side and the text on the right side, as per the indd file. Thanks

**Comment by halfempty** [comment]
@gehalber Okay, the ACF fields are back on the edit screen, with spots for the image. Plus I've put in the styles:

http://jsa.etc-nyc.com/people/
