### ISSUE TITLE
List Page Template

### ISSUE THREAD

**Issue by halfempty** [everythingtype/jsa#21]
- Used for Exhibitions, Essays & Awards, Press
- External Links
- Internal Links to Posts and Pages

**Comment by halfempty** [comment]
@gehalber The pages using the List template are ready to receive content. They are:

- Exhibitions
- Essays
- Articles
- Awards
- Competitions
- Fellowships
- Press

(I may need to explain how the "internal links" work. If they have any of those ready to go let me know and I'll prep an example.) 

The front-end styles aren't complete yet.

**Comment by gehalber** [comment]
Hi Marty,

I think I figured out how to do the internal post. In order to make an internal link for exhibitions say, would I just make a new post and then create a new category called “Exhbitions”?

—g

**Comment by halfempty** [comment]
Add a bit of formatting to the list on this template

**Comment by gehalber** [comment]
Couple of changes to this. 
• Years should be in black
• Hyper linked items should be in gray (both title and subtitle)
• Non linked items should appear in black (both title and subtitle)

**Comment by halfempty** [comment]
Got it, done!

**Comment by gehalber** [comment]
Can you make the gray type hover to black. thanks!

**Comment by halfempty** [comment]
Done
