### ISSUE TITLE
Default Page Template

### ISSUE THREAD

**Issue by halfempty** [everythingtype/jsa#22]
- Research Interior
- Profile

**Comment by halfempty** [comment]
@gehalber The layout of this template is pretty straightforward. I've put in the margins, as visible here:

http://jsa.etc-nyc.com/research/interface-landscape-architecture/

**Comment by gehalber** [comment]
This looks great!
Can you also drop in a headline field for this that is the same size as the nav. I think we may need it.

**Comment by halfempty** [comment]
@gehalber Like so?

![image](https://cloud.githubusercontent.com/assets/775543/7826241/1ade5c24-03dd-11e5-9606-6ddf278b859e.png)
