### ISSUE TITLE
Sort Project Categories on the fly using Packery

### ISSUE THREAD

**Issue by halfempty** [everythingtype/jsa#26]
@gehalber The Projects menu in the InDesigns shows just twp layers of depth. That is:

` PROJECTS ->  Institutional / Residential / Public Space`

But in the CMS I'm seeing a third. That is, subcategories of each of the three.

Can I safely remove these from the Menus, to match the InDesigns?

**Comment by gehalber** [comment]
There are subcategories for each of the menu items. 
See page 11 in the Indesign doc.

**Comment by halfempty** [comment]
@gehalber I've made some progress on this. You should now be able to browse around using the nav.

A couple of bugs do remain, which remain on my list:

- The main nav on the "About" section is pushing down under the secondary nav
- There's sometimes a flash at page load, as elements situate themselves

**Comment by halfempty** [comment]
@gehalber Okay, the project category pages should be back up and running again. Please take a look!

**Comment by gehalber** [comment]
Very cool Marty! Site is looking really great!
One question: would it be possible to sort these categories on the fly using packery (ala YBCA)?

**Comment by halfempty** [comment]
@gehalber This one's complicated. A bit of explanation / thinking out loud...

We don't want to make our navigation dependent of JavaScript. It's a principal of good development that we should provide an HTML-only fallback for situations where JS is either not available (nowadays rare) or for whatever reason fails (more common, especially given flakey cell connections). Since we have the HTML version working, the task here will be to layer a JS scheme on top.

Another aspect I'm thinking about is that I don't want to load non-relevant thumbs in situation where someone has navigated directly to one of the sub-categories. My reasons are a) WordPress doesn't really make it easy; b) because of the JS-less perspective articulated above, I don't want those items printed on the page; and c) from a bandwidth perspective I don't want unused images to be loaded. This leads me to...

I suggest that we use Packery when someone has landed on the root "Projects" page, and are then drilling down. But if the person is directly hitting one of the sub-categories, let's use the existing HTML links. Then, if they wander back up to root Projects, Packery will kick in when they begin to drill back down. Makes sense? Sound okay?

**Comment by gehalber** [comment]
This makes sense. Perfect.
