### ISSUE TITLE
Fixed Header

### ISSUE THREAD

**Issue by halfempty** [everythingtype/jsa#27]
@gehalber 

I've fixed the header. And when you scroll down a bit, the grey line fades in.

There's something about it I want to spend a bit more time on, however. On my Air, I can sometimes make the header stutter-- like it can't keep up with the scrolling, especially if other things are moving on the page.

I suspect this might have to do with the test that turns the grey line on and off, which fires continuously during scrolling. I want to take a look to see if there's a way to code this in a more RAM-efficient way.

**Comment by halfempty** [comment]
Oops, duplicate issue. Closing.

**Comment by gehalber** [comment]
ok great.
