### ISSUE TITLE
Related Projects

### ISSUE THREAD

**Issue by halfempty** [everythingtype/jsa#28]
- This is for the "related projects" block at the bottom of the Project page
- Also appears on Research pages

**Comment by gehalber** [comment]
We aren't going to do remove the screen affect from the original designs 
Updated designs on pg 32 of jsa-design-20-website-calibre-full.indd
including back button

**Comment by halfempty** [comment]
Okay, this is in.

Regarding pages: The Related Projects bit has been added to the default page template, 'cause this is the one the Research texts use. Projects can be associated with any Page, but they'll only appear on ones using this template. If it turns out they need them on other templates too (and other types, such as Poses), we can add it in.
