### ISSUE TITLE
Final Indesign Files

### ISSUE THREAD

**Issue by gehalber** [everythingtype/jsa#3]
These are located in your folder Marty inside the JSA folder called:

Final Design-desktop-mobile Folder

Please note that the main font has changed from Executive to Calibre.

**Comment by devinsays** [comment]
@halfempty My InDesign trial expired and its not something I necessarily need to own. Would you mind converting one or two of these layouts to PSD just so I can measure sizes and paddings?

**Comment by devinsays** [comment]
Nevermind, I'll just upgrade for the month. Closing ticket out.
