### ISSUE TITLE
Slide Type: Side-By-Side

### ISSUE THREAD

**Issue by halfempty** [everythingtype/jsa#30]

**Comment by halfempty** [comment]
@gehalber Off the top of your head, can you point me to an example of this slide-type on the site?

**Comment by gehalber** [comment]
in the mockups or the actual site?

If on the site, go ahead and just concoct a version of that and we’ll flag it for them to change before launch.

**Comment by halfempty** [comment]
@gehalber I've added a side-by-side to this Page (near the bottom):

http://jsa.etc-nyc.com/project/vitale-loft/

Take a look and let me know if it's what you had in mind? Thanks!

**Comment by gehalber** [comment]
Just one tweak: the right hand image would be left aligned in that right hand column

**Comment by halfempty** [comment]
Okay, tweaked.
