### ISSUE TITLE
Order of Items in List Template

### ISSUE THREAD

**Issue by halfempty** [everythingtype/jsa#32]
**@gehalber says:**

> Is it possible to auto sort the list template by year? And then list each item alphabetically?

**Comment by halfempty** [comment]
@gehalber Yes, it is. However, it's labour intensive -- measured in hours, not minutes. It will also mean that a certain amount of flexibility will be lost-- there'll be no fudging of the fields possible. (Right now you can put something other than a strict four-digit year in the Year field, for instance, if you need to.)

What I'm saying is if they really want it, I can certainly do it! But if it's more of a "fix it if it's quick"-type request, they might not want to.

**Comment by gehalber** [comment]
This seems to be working fine for them. I'm going to close.
