### ISSUE TITLE
Project Order in Categories

### ISSUE THREAD

**Issue by halfempty** [everythingtype/jsa#33]
**@gehalber says:**

> How are projects ordered on the project landing page? Can this be ordered chronologically?

**Comment by halfempty** [comment]
@gehalber Okay, this is in. I first tried doing this using the existing "Year" field. However, I noticed that some projects have ranges in that field, which made it very difficult to sort with. So instead, I surfaced a field WP provides specifically for ordering Posts.

It's called, straightforwardly, "Order", and it now appears in the right-hand column of the Edit Project screen. It is not presented visually on the front-end, and is only used for ordering. Here's what it looks like:

![image](https://cloud.githubusercontent.com/assets/775543/7951090/b3ed63ac-0968-11e5-9b28-8a737f253c5c.png)

I've gone in and updated the Projects already in the system. When adding new projects, Josh should please remember to fill-in this field with a simple four-digit year.

**Comment by gehalber** [comment]
How would we apply this to the elements of the list? It looks more like an attribute for the page…

**Comment by halfempty** [comment]
@gehalber Yes, this one is for the Projects, and how they appear on project categories.

Did you mean something else?

**Comment by gehalber** [comment]
Oh, I see. That wasn’t the issue. It was on pages in About: exhibitions, publications, awards…

They wanted to find a way to have the listing chronologically by year itself. What do you think?

**Comment by halfempty** [comment]
Oh, that's this one:
https://github.com/everythingtype/jsa/issues/32
