### ISSUE TITLE
User Permissions

### ISSUE THREAD

**Issue by halfempty** [everythingtype/jsa#34]
**@gehalber says:**

> Is it possible to for a user to update the carousel images on homepage? Or is that something you have to do? Regardless, this should be an admin role only. Also, can you set it so that Admin is the only person to edit page templates?

**Comment by halfempty** [comment]
@gehalber The homepage carousel can be updated, yes. There are ACF fields for it.

In terms of permissions, there's a plugin (called "Members") that will let us get pretty granular with it.

But for clarity, let me ask about the other side of what you're asking: Are there people you only want to have access to some things, but not others? If yes, what SHOULD they have access to?

**Comment by gehalber** [comment]
For now, let’s table this until the end of the site. Thanks though.
