### ISSUE TITLE
Fallback Thumbanil

### ISSUE THREAD

**Issue by halfempty** [everythingtype/jsa#35]
**@gehalber said:**

> Every project and news should have an image, but in case one doesn’t we can come up with a placeholder.

This is a reminder that we need to choose an image for this, then set it as the fallback.

**Comment by gehalber** [comment]
Let's do something like this: the dot pattern svg on top of the "gray" color background...

![screen shot 2015-06-17 at 4 04 39 pm](https://cloud.githubusercontent.com/assets/6076488/8217336/cbeae21a-150a-11e5-8624-7c50172db6ec.png)

**Comment by gehalber** [comment]
the box on the right side

**Comment by halfempty** [comment]
@gehalber Okay, like this?

![image](https://cloud.githubusercontent.com/assets/775543/8239784/b451bf70-15c3-11e5-83f4-a6d4e35cc5b2.png)

(mesh is visible even when no mouseover)

**Comment by gehalber** [comment]
nice!
