### ISSUE TITLE
Faux Bold

### ISSUE THREAD

**Issue by halfempty** [everythingtype/jsa#37]
@gehalber,

I notice the client has been setting some text in bold. Since we haven't uploaded a WOFF file for it, it's faux and looks rather bad:

![image](https://cloud.githubusercontent.com/assets/775543/7976581/f5c327aa-0a42-11e5-9416-e34b53d0ead5.png)

The larger question is that we're not using bold anywhere-- it's not part of the look. What to do?

**Comment by gehalber** [comment]
I'll talk to them about it tomorrow. 
No sweat.

**Comment by gehalber** [comment]
We are going to allow for the bolds in instances such as the above. Do you have the bold font?

**Comment by halfempty** [comment]
I don't have the webfont for bold. Can you get it and send it over? Thanks!

**Comment by halfempty** [comment]
@gehalber Would love to get the proper webfont in there. Can you pick it up? Or should I?

**Comment by gehalber** [comment]
JSA is getting this for Monday. Will forward it over.

**Comment by halfempty** [comment]
@gehalber Okay, Bold is in. We don't have *Bold Italic*, tho. Looks like this:

![image](https://cloud.githubusercontent.com/assets/775543/8315108/ca0ce9fe-19b3-11e5-9769-87662b21ab86.png)

(Also, just thinking out loud, would Medium be a better match in this situation than Bold?)

**Comment by gehalber** [comment]
mmmm. you’re probably right.
ok. I’ll reach out about that.

thanks!
