### ISSUE TITLE
Flickity: autoplay on hover

### ISSUE THREAD

**Issue by gehalber** [everythingtype/jsa#38]
After you've clicked into the site from splash let's have the carousel automatically slide ever few seconds.

**Comment by halfempty** [comment]
@gehalber If I understand your note correctly... 

What's happening here is that the carousel pauses when you're mousing-over one of the slides. I found a discussion on it, where the developer explained his reasoning for this-- it's a usability best practice.

Should I put together a work-around? That is to ask, how strongly do we feel about having the slides autoplay, even if you're mousing-over? Pretty strongly?
