### ISSUE TITLE
Website Hosting

### ISSUE THREAD

**Issue by gehalber** [everythingtype/jsa#4]
JSA currently uses Site5: http://www.site5.com/
What do you think?

**Comment by halfempty** [comment]
@gehalber It looks like their Site5 account supports databases, which means it should support WordPress. I would suggest creating a subdomain on their account -- "dev.joelsandersarchitect.com" for instance -- and install WP there as a confirmation. Please let me know if they're cool with that!

**Comment by gehalber** [comment]
Let’s do it!

**Comment by halfempty** [comment]
We've determined that Site 5 will be okay for this, so closing this issue.
