### ISSUE TITLE
Image Hover

### ISSUE THREAD

**Issue by gehalber** [everythingtype/jsa#40]
refine screen-dots to fit project thumbnails. The right edge is a little funky. Should we send you a new image?

**Comment by halfempty** [comment]
@gehalber Yes, a new graphic would be super

**Comment by KyleETC** [comment]
Here's a new graphic for the image hover. I've tried to resolve the issue of the funky edge along the right and bottom of the image. This may be difficult to correct with the pattern being repeated and how it relates to the various image widths. Open to suggestions if this doesn't remedy the problem.

https://www.dropbox.com/s/mh9rcplbmt7lluj/JSA-Dot-Uniform-04.svg?dl=0

**Comment by halfempty** [comment]
@KyleETC You know what, there is one other way we could try. Instead of having a smaller image that repeats, we could have one large image that scales to fit the available width. The CSS setting is called "cover". I'll try it...

**Comment by halfempty** [comment]
@KyleETC Actually, you might already have the files needed to do this. May I ask you to create the graphic? What we need is an 390 x 245 SVG. 

Let me know, thanks!

**Comment by KyleETC** [comment]
Sure thing, I will set this up for you tonight.

**Comment by gehalber** [comment]
@KyleETC I'll add to Basecamp too...

**Comment by KyleETC** [comment]
I will handle this tonight.

**Comment by KyleETC** [comment]
Here is the revised hover graphic at 390 x 245 SVG. Hopefully, this works!
https://www.dropbox.com/s/b7vt4vrh9piy3yy/JSA-390x245-white.svgz?dl=0

**Comment by halfempty** [comment]
Okay, this is in!
