### ISSUE TITLE
Featured items in About: Exhibitions, Essays, Articles etc

### ISSUE THREAD

**Issue by gehalber** [everythingtype/jsa#41]
This would work just like the "Featured Projects" and "news" on the homepage

**Comment by halfempty** [comment]
@gehalber Okay, for this one... I've added the ability for items in a list to be marked as "featured".  The items so-marked are then presented in a grid above the list. Here's an example:

http://jsa.etc-nyc.com/articles/

When you check the box for this in the backend, you're given a field in which to specify which image to use. If you don't specify an image, it won't show in the grid.

Please take a look and let me know how it looks. (And you'll want to un-feature the items once you've had a look, 'cause I just picked them at random and added non-related images.)

**Comment by halfempty** [comment]
Ps. Just stepped away from my computer and am realizing the links in this grid might not be active. Will update in a moment.

**Comment by halfempty** [comment]
@gehalber Okay, links active now
