### ISSUE TITLE
Contact Page

### ISSUE THREAD

**Issue by gehalber** [everythingtype/jsa#47]
This page should be completed for the launch

**Comment by halfempty** [comment]
@gehalber The content on this one is currently a lot less than what's shown in the mockup. Should I put in the maps? And not worry about the stuff shown below?

**Comment by gehalber** [comment]
The content should be the same as what’s in the mockup. Should I drop that in so you can style it?

**Comment by halfempty** [comment]
@gehalber What's JSA's Shanghai address? It's not in the mockups or on their old site?

**Comment by gehalber** [comment]
Its not in existence yet, but it may be in the future. 
Perhaps that is something we can just add in later?

**Comment by halfempty** [comment]
@gehalber Please take a look:

http://jsa.etc-nyc.com/contact/

**Comment by gehalber** [comment]
This looks really good.

For the map, let's use this guy: https://snazzymaps.com/style/132/light-gray

Can the gray be the gray we're using on the rest of the site?

One tweak: Between the subheads (eg PRESS INQUIRIES) and body text it should be one full space, or 68px from base to baseline. Can you tweak that?

**Comment by halfempty** [comment]
@gehalber Okay, these are in.
