### ISSUE TITLE
IE: No splash SVG

### ISSUE THREAD

**Issue by halfempty** [everythingtype/jsa#48]
On IE, he splash SVG logo doesn't appear. For this browser, it needs to be replaced by a PNG.

**Comment by gehalber** [comment]
ok. do you need us to make? or?

**Comment by halfempty** [comment]
Okay, fixed

**Comment by halfempty** [comment]
Not fixed. The same problem happens in FF...

**Comment by halfempty** [comment]
Okay, now fixed (I hope!)
