### ISSUE TITLE
add social media to news

### ISSUE THREAD

**Issue by gehalber** [everythingtype/jsa#49]
See indesign docs

**Comment by gehalber** [comment]
also this feature should be added to books too

**Comment by halfempty** [comment]
@gehalber okay, these are in. Of those services, I have Twitter and can confirm the links are correct. Can someone with accounts on those other services confirm they work as well? (Maybe Josh has them?)

**Comment by halfempty** [comment]
@gehalber I'm going to go ahead and close this.
