### ISSUE TITLE
Fonts

### ISSUE THREAD

**Issue by gehalber** [everythingtype/jsa#5]
These are in the dropbox folder...

**Comment by devinsays** [comment]
@gehalber I'm seeing the .ttf version. Were any other files including with your download? Specifically looking for webfont files (woff, .svg, .eot) and any include code that came with it.

https://klim.co.nz/retail-fonts/calibre

**Comment by gehalber** [comment]
I’m asking about it. I didn’t purchase, so might have been an error purchase. I’ll update when I find out.

**Comment by gehalber** [comment]
woff and eot fonts are in the folder…

**Comment by gehalber** [comment]
Closing this out...
