### ISSUE TITLE
Splash page: automatic entrance

### ISSUE THREAD

**Issue by gehalber** [everythingtype/jsa#52]
Is it possible to automatically fade into the carousel after a set amount of time or a mouse click required?

**Comment by halfempty** [comment]
@gehalber we can make it automatic. How long?

**Comment by gehalber** [comment]
5 seconds to start…

**Comment by gehalber** [comment]
Do you know when you'll be able to complete this?

**Comment by halfempty** [comment]
@gehalber No time at all! Done.
