### ISSUE TITLE
Projects Grid Order

### ISSUE THREAD

**Issue by gehalber** [everythingtype/jsa#54]
sort by start year, then alphabetical (currently sorting by end year, if a range)...

This possible?

**Comment by halfempty** [comment]
@gehalber The sorting is done by field called `menu_order`, which is in a box on the edit screen. It's on the right-hand column and looks like this:

![image](https://cloud.githubusercontent.com/assets/775543/8440704/988ed38e-1f39-11e5-9edc-c84417f408d6.png)

So it's not sorting by End Year exactly, it's sorted by whichever number is put into that box. And it's Descending order, meaning higher numbers first.

I put those numbers in when I was working on this aspect, and I may have used the end years. If the client would like to tweak them, he should have at it! (Unless you'd like me to go in, though I'm less familiar with the projects so it'd might take a bit longer.)

For projects with the same Menu Order, it's going by the order they were created in the system. I can change this by adding a parameter to sub-sort by Title. However, Descending is going to still apply, so it'd be Z-first, A-last. As with most things, it IS possible to program around this and get exactly the effect you're describing, but it would take a substantial amount of coding.

**Comment by gehalber** [comment]
Ok. Great. Let's put this in their court.
