### ISSUE TITLE
Related on Research pages

### ISSUE THREAD

**Issue by gehalber** [everythingtype/jsa#56]
Is related projects enabled on the site yet for projects and/or research pages?

**Comment by halfempty** [comment]
@gehalber 

Projects can be related to each other, and Related Projects are displayed at the bottom of the Project template. The connection is reciprocal. 

Projects can be related to Pages, and Related Projects are displayed at the bottom of the Default Page template. The Pages are not reciprocally shown at the bottom of the project template.

The specialty page templates -- like the one of the Research landing page, or the lists -- don't include the related bit. Would you like them to?

**Comment by gehalber** [comment]
No. I think we're good for now. Thanks!
