### ISSUE TITLE
Address images load times

### ISSUE THREAD

**Issue by halfempty** [everythingtype/jsa#63]

**Comment by halfempty** [comment]
@gehalber I've applied a couple of changes for this. The concern, I think, was mainly with the thumbnails. I've adjusted them and they're loading fast for me now. (The images on the project page were already pretty much where they should be.)

Clear your cache and take a look? Thanks!

http://joelsandersarchitect.com/projects/
I'll need to adjust these again when we apply responsive as the display size of the thumbnails will jump around with the number of columns.

**Comment by gehalber** [comment]
Much faster!

**Comment by halfempty** [comment]
Great! Closing this...
