### ISSUE TITLE
Social media icons

### ISSUE THREAD

**Issue by halfempty** [everythingtype/jsa#65]
@gehalber I've put in the icons. Can you tell me the URLs where each should link? Thanks!

**Comment by gehalber** [comment]
Facebook: https://www.facebook.com/joelsandersarchitect
Twitter: https://twitter.com/joelsandersarc/
Architizer: http://www.architizer.com/en_us/firms/view/joel-sanders-architect/364/
LinkedIn: https://www.linkedin.com/company/joel-sanders-architect
Youtube: https://www.youtube.com/user/JoelSandersArch?ob=0&feature=results_main
Instagram: https://www.instagram.com/jsa_joelsandersarchitect/

**Comment by halfempty** [comment]
@gehalber Done.

Reminder: They need to update their logos on Twitter and Architizer.

Also, their Youtube channel hasn't been updated in 4 years. Unless they're going to update it, I wouldn't include it.

**Comment by gehalber** [comment]
Ha!

**Comment by halfempty** [comment]
@gehalber should i remove it? or no?

**Comment by gehalber** [comment]
Let's keep it for now, at least until I can razz Josh about it.

**Comment by gehalber** [comment]
Can you make these links open up in another tab?

**Comment by halfempty** [comment]
Done
