### ISSUE TITLE
Add Featured module to Archive templates

### ISSUE THREAD

**Issue by halfempty** [everythingtype/jsa#67]
@gehalber We've got this item in the estimate. Can you remind me about it? 

We already have Featured on the "List" template, which is the one used for Exhibitions and the like. So does this item refer to putting Featured on the template used by Books and News? If so, is this still something they want?

**Comment by gehalber** [comment]
Oh, that’s already working?
It looks like this. We only need featured for lists.

**Comment by halfempty** [comment]
@gehalber So we're good on this one, right? I'll close this. Reopen if need be.
