### ISSUE TITLE
Add image carousel to News / Books

### ISSUE THREAD

**Issue by halfempty** [everythingtype/jsa#68]

**Comment by halfempty** [comment]
@gehalber I've put this in. Will you review and give feedback? Thanks! Here's an example:

http://dev.joelsandersarchitect.com/lecture-for-the-swedish-association-of-architects-gala/

**Comment by gehalber** [comment]
Thanks. Can you drop in the arrows too? I think the dots had a little bit more space between them too. See image:

**Comment by halfempty** [comment]
@gehalber That image didn't come through. Can you repost? Thanks!

**Comment by halfempty** [comment]
@gehalber Arrows are in. You might want them changed. Let me know! 

http://dev.joelsandersarchitect.com/lecture-for-the-swedish-association-of-architects-gala/

**Comment by gehalber** [comment]
![screen shot 2016-03-08 at 3 33 03 pm](https://cloud.githubusercontent.com/assets/6076488/13656631/81a4f710-e636-11e5-9de4-f7ec71756401.png)

**Comment by halfempty** [comment]
@gehalber Got it!
