### ISSUE TITLE
Reformat Contact page to allow for satellite offices

### ISSUE THREAD

**Issue by halfempty** [everythingtype/jsa#69]

**Comment by halfempty** [comment]
@gehalber Okay, this is in:

http://dev.joelsandersarchitect.com/contact/

**Comment by gehalber** [comment]
Can we try making all of this type font-size 22; line-height: 26?

**Comment by halfempty** [comment]
Okay 22 / 26 is in. (Btw the global style is 22 / 24)

**Comment by gehalber** [comment]
Perfect. We should update the global style to be 22/26. Thanks!
