### ISSUE TITLE
Backend: Project Details

### ISSUE THREAD

**Issue by gehalber** [everythingtype/jsa#7]
Is there a way we can add dropdowns to the Labels within Project Details? It would be nice to have a set of labels to maintain consistency and for ease of use.

What do you think?

**Comment by halfempty** [comment]
@gehalber It would be good to have this in the correct format in-time for content upload. To make this change we'll need a list of all the possible values to include.

**Comment by gehalber** [comment]
For now:
Year
Architect
Landscape Architect

Will it be easy to add more later?

**Comment by gehalber** [comment]
Please add these others as well:
Location
Size
Scope

**Comment by halfempty** [comment]
@gehalber Okay, this is updated. I've changed the format of the fields, but I hope it's still obvious/intuitive how to use it.
