### ISSUE TITLE
Custom Google Map colorway

### ISSUE THREAD

**Issue by halfempty** [everythingtype/jsa#70]
We we (you?) able to get this how you wanted? Or is there still more to do? Here's the present color:

![image](https://cloud.githubusercontent.com/assets/775543/13648104/b610f7fe-e5fc-11e5-99aa-1bb297180d8e.png)

**Comment by halfempty** [comment]
@gehalber Ps. We used "SnazzyMaps", right? I see it in the code...

**Comment by gehalber** [comment]
Yes.

**Comment by gehalber** [comment]
Josh sent me this:
https://developers.google.com/maps/documentation/javascript/examples/marker-animations

They like the animation. Could we implement that with the snazzy maps gray, or are those two things competing?

**Comment by halfempty** [comment]
@gehalber okay, this is in
