### ISSUE TITLE
Splash & Homepage changes

### ISSUE THREAD

**Issue by halfempty** [everythingtype/jsa#71]

**Comment by halfempty** [comment]
@gehalber Hi guys. This is in, for the most part. 

- I've put in the new styling on the Splash. I've also switched it to a "roll-up" rather than "fade-out", 'cause that's more consistent with the down-arrow indicator. What do you think, will that work?

- And then, on Home, I adjusted the carousel so that the images always fill the window (which was not the case previously).

- The slide labels are attached to the slides themselves, so they slide-in with the image. I attempted to remove them from that flow and have them sit statically next to the dots, which would be a more subtle effect. But that turned out to be a complex puzzle, so didn't purse it. We can come back to it if it's something that bothers you.

- I didn't put the white down-arrow on the carousel because this placement would put it directly behind the clear down-arrow on the splash, having the effect of filling it in. You know what I mean? It's my feeling that in 2016 people don't exactly need a reminder to scroll down pages, so I would advocate simply dropping that arrow. Otherwise, could we align it to the right, so that it's not directly aligned to the other one?

**Comment by gehalber** [comment]
Looking really sweet! A few thoughts:

For homepage, we’re thinking it would be better to remove the arrow from the landing screen, especially if it automatically reveals itself. And then place the arrow on the carousel which after clicking it anchors you down.
Let’s slow down the time lapse between slides. It should just feel a little more relaxed. Maybe it slides every 3 seconds.
Totally happy with the slide labels sliding. Looks good.
Psyched about the way the images fill the screen. Very cool!
Is this landing screen something that could exist on mobile too?

**Comment by halfempty** [comment]
@gehalber Okay, these changes are in.

> Is this landing screen something that could exist on mobile too?

I can see a couple of problems with it. One would be that the images underneath don't fill the window, so the transparent JSA logo effect would be compromised.

Another is that, when you're standing there on your phone, do you really want another tap / a few more seconds? My feeling is that it's best to get straight to the content.

I could see bringing the splash and associated design elements back at tablet sizes, though. Maybe that's something we could return to later in the process if we've got time?

**Comment by gehalber** [comment]
This looks awesome!
