### ISSUE TITLE
Project template

### ISSUE THREAD

**Issue by halfempty** [everythingtype/jsa#73]

**Comment by halfempty** [comment]
@gehalber Question about the double-image slide. Is the logic that... 
- there's two columns, each 50% of the width
- Images are aligned to the left side of the column

Is there a gutter, in case both images are landscape?

Bigger question... I see cases where the client is making his own doubles in PhotoShop. In light of this, should we even keep developing this slide type?

**Comment by gehalber** [comment]
yes. Two columns. Each 50% of the width.
Images are centered on the column.

We will talk to the client about their photoshopping. I want to keep our double up style.

Does that answer your questions?

**Comment by halfempty** [comment]
@gehalber yes, except in the InDesign you're showing the images left-aligned. I'll do center. And I'm seeing that 30px gutter, so I'll do that as well.

**Comment by gehalber** [comment]
Cool. Horizontal images are full column. Vertical images are centered and set height …

**Comment by halfempty** [comment]
@gehalber Okay, here's what I was able to put in:

- Removed "Info" from the top nav
- The second item is now the description, which has been reformatted.
- A grey box is in-place of where the description image will be.
- The reconfigured layout of the dual-image slides.
- The reconfigured layout of the "Related projects" area

Here's what I see in the comps but haven't yet put in:

- The "read more/read less" link. This isn't going to be the simplest thing to put in, especially if we want to make it easy for the client to use. If at all possible, it would be my inclination to drop this feature.
- The description image needs to be finished, on aspect of which will be the creation of a field in the admin so that this image can be specified.
- Video slides. Haven't started on that yet.
- The up-arrow sitting in the bottom-right of the window.

Anything I missed?
