### ISSUE TITLE
Project template: The "read more/read less" link.

### ISSUE THREAD

**Issue by halfempty** [everythingtype/jsa#74]
We'll do this with paragraphs.

**Comment by gehalber** [comment]
I think so. Let me first confirm that will work for them.

**Comment by gehalber** [comment]
Ok. This has been approved. You can go ahead and employ this functionality. Thanks!

**Comment by halfempty** [comment]
@gehalber Done. Example:

http://dev.joelsandersarchitect.com/project/nyu-bobst-library/
