### ISSUE TITLE
Project template: The description image 

### ISSUE THREAD

**Issue by halfempty** [everythingtype/jsa#75]

**Comment by halfempty** [comment]
**@gehalber asks:**

> On the project page, you don’t have the functionality yet built in for adding the image to the right of the info text, right?

Not yet!

**Comment by halfempty** [comment]
**@gehalber says:**

> Right now the project info/image diptych appears to have the image aligned to the right side...

We should talk about this image using this thread, to keep things straight... Right now this image box is 50%. When I put the image in here, I will horizontally align it. 

But for vertical alignment, I'm not sure. The reason is that the height of the accompanying text column (to the left) is variable. And when the user clicks "Read more" and "Read less" the height will change.

We could conceivably set the hight of the image box to the height of the available window (as we do on the other slides) but, for the effort that will take (I'm still struggling to get the diptych slides correct in Firefox) it will be low bang-for-buck. That is, would that behavior even be noticeable vs simply centering within a square container?

**Comment by halfempty** [comment]
@gehalber Ps, it is doing this right now, which I need to fix:

![image](https://cloud.githubusercontent.com/assets/775543/13931973/e609bb1e-ef73-11e5-9096-e436e4a6bbd9.png)

It should be 50%, which is maybe what you were saying, actually?

**Comment by gehalber** [comment]
I think the vertical alignment should align with the top of the text box to the left.

**Comment by halfempty** [comment]
@gehalber 10-4!

**Comment by halfempty** [comment]
@gehalber Okay, I think this is in. Please take a look! And you can Edit the page to see the interface for it and change the image to one with landscape-orientation.

**Comment by gehalber** [comment]
I think we just need to add the less and more bit. We did get approval on splitting these up as paragraphs.
