### ISSUE TITLE
Project template: diptych alignment

### ISSUE THREAD

**Issue by halfempty** [everythingtype/jsa#76]
The images aren't vertically centering

**Comment by halfempty** [comment]
@gehalber Take a look here, at the slide following the description:

http://dev.joelsandersarchitect.com/project/nyu-bobst-library/

Is this the desired alignment?

(Note that it should be displaying correctly in Chrome, but FireFox is stretching the image incorrectly.)

**Comment by gehalber** [comment]
Cool. I think we should keep with this for now. If we need to change the alignment later will that be easy to do?

**Comment by halfempty** [comment]
@gehalber Change how?

**Comment by gehalber** [comment]
Right now, its currently right aligning to the right edge. It does look good, but what if we decided we wanted to center it between center column and right edge?

**Comment by halfempty** [comment]
@gehalber I'm not sure I understand? Here's what they're doing, centered both horizontally and vertically. With a 30px gutter.

![image](https://cloud.githubusercontent.com/assets/775543/13931008/5d82cb5e-ef6f-11e5-91b7-80cdac9dd9c9.png)

![image](https://cloud.githubusercontent.com/assets/775543/13931002/5940e80a-ef6f-11e5-8e3d-445f964cafc5.png)

**Comment by gehalber** [comment]
Sorry, Marty. I’m confusing the project info/image diptych and the double image diptych. Ultimately I think these should have the same principles. Can you center the vertical images in both instances? Right now the project info/image diptych appears to have the image aligned to the right side...

**Comment by halfempty** [comment]
@gehalber This still has the issue in Firefox

**Comment by gehalber** [comment]
ok

**Comment by halfempty** [comment]
Fixed
