### ISSUE TITLE
Project template: Video slides

### ISSUE THREAD

**Issue by halfempty** [everythingtype/jsa#77]

**Comment by halfempty** [comment]
@gehalber The back-end for video is in. The front-end's fairly complex, though. I had hoped to get it partially in, but I've realized it's not going to look right unless it's really done, so I haven't included it for tomorrow.

**Comment by halfempty** [comment]
@gehalber Take a look at this, the slide following the description:

http://dev.joelsandersarchitect.com/project/39-west-23rd/

Youtube autoplay's not as smooth as what we were getting with vimeo, but does it work for you?

Also, do you think y'all could send me "neutral" and "hover" versions of the Play button? I'm having trouble pulling these out of the Indesign. Vector format would be best.Thanks!

**Comment by gehalber** [comment]
This works fine for me. We'll send icons tomorrow.

**Comment by halfempty** [comment]
@gehalber Do you have the "play" icons ready? The video and homepage changes are in together, so I'd like to get video in a presentable state before pushing the code.

**Comment by gehalber** [comment]
I’ll make those now! Thanks for letting me know.

**Comment by gehalber** [comment]
Was having trouble making these svgs. Here are pngs in 2 sizes...
https://www.dropbox.com/sh/wluxdkp4dca7ujo/AADnPbiKIt5_b3P5sIlrx9O7a?dl=0

**Comment by halfempty** [comment]
@gehalber Okay these are in.

http://dev.joelsandersarchitect.com/project/39-west-23rd/

I'm going to push live.

**Comment by gehalber** [comment]
Ok. Cool!

**Comment by halfempty** [comment]
Done

**Comment by gehalber** [comment]
Live?

**Comment by halfempty** [comment]
@gehalber Yes

**Comment by KyleETC** [comment]
Well done fellas! I spent a little time trying to break this yesterday.
Looking so good… 

KB

Kyle Blue
Partner & Creative Director

ETC
561 Myrtle Avenue
2nd Floor
Brooklyn, NY 11205

347-587-9315
www.etc-nyc.com <http://www.etc-nyc.com/>

**Comment by gehalber** [comment]
Marty, from Josh... Can you tweak the video slide accordingly. They really need this done today in order to launch tomorrow. Think you could make that happen?

I just played with resizing the window and see where the responsive mechanics are making the video window seem weird with black bars. Is it possible to resize the video window to max width or height according to screen sizes, but not to allow black margins top/bottom or left/right? This would solve the problem. Can this be changed today?

Thx,
J

**Comment by halfempty** [comment]
@gehalber No, that's not going to be possible. I did investigate doing it that way, but there was an underlying technical issue:

When using oEmbed with Advanced Custom Fields, WordPress returns a fully-formed Embed object that hasn't been filtered by Fluid Video Embeds.

**Comment by gehalber** [comment]
Not totally sure what that means, but I’ll relay its not possible. 
I guess they’ll have to tweak their videos to be the same proportion as images?

**Comment by gehalber** [comment]
Can you confirm that the video slides are pushed live? They can't see them...

Thanks!
