### ISSUE TITLE
Up arrow

### ISSUE THREAD

**Issue by halfempty** [everythingtype/jsa#78]
The up-arrow sitting in the bottom-right of the window.

**Comment by halfempty** [comment]
@gehalber To confirm: This "back to top" arrow is on the Project template only, right?

**Comment by gehalber** [comment]
I think we want it on all. 
Is that harder?

**Comment by halfempty** [comment]
@gehalber Okay, this is in. Will you confirm the look / placement?

**Comment by gehalber** [comment]
Can you tuck this down closer to bottom?
Maybe 40px from bottom...

**Comment by halfempty** [comment]
@gehalber Okay, look now?

**Comment by gehalber** [comment]
There was a weird thing that was happening during the demo. When hovering over the image the cursor would change to the arrow, then when I went down to the up arrow, the cursor wouldn't change back. Is it a z-index thing? Should the up arrow be in front of everything else?

**Comment by halfempty** [comment]
@gehalber I've changed the z-index. Check if it's helped?

**Comment by gehalber** [comment]
Yes. Thanks!
