### ISSUE TITLE
Splash timing

### ISSUE THREAD

**Issue by halfempty** [everythingtype/jsa#84]
**@gehalber says:**

> On the homepage, let’s have the shade automatically reveal the image behind it after a little bit of time. 6, 7, 8 seconds? What do you think?

**Comment by halfempty** [comment]
@gehalber , here's 8 seconds:

http://dev.joelsandersarchitect.com/

**Comment by gehalber** [comment]
That seems fine, but we should speed up the carousel to 4 seconds.

**Comment by halfempty** [comment]
@gehalber Oh wait, I erred. I had set the carousel to 8.

Okay, now the carousel is 4.5 sec and the splash is 8 sec.

**Comment by gehalber** [comment]
cool.

In your opinion do you think the splash should only move on mouse click? 

Another question for you. Say we wanted to create a screen saver for this site, where after a minute of inactivity the screen gets taken over by a new graphic. We were imagining it is just the JSA splash screen with carousel behind it. And moving your mouse or clicking would just take you back to the page you were on.

Is that something difficult to do?

**Comment by gehalber** [comment]
Change the carousel timing to 3.5 seconds. And the splash reveal to 9 seconds.

**Comment by halfempty** [comment]
Done
