### ISSUE TITLE
Video looping

### ISSUE THREAD

**Issue by gehalber** [everythingtype/jsa#89]
If they set video to loop in youtube, will it loop on the front end?

**Comment by gehalber** [comment]
Any thoughts on this, can wordpress allow looping to happen, or should they go this route? 

(comment from JSA)

For the GIF videos: I have created the slideshow of images on Youtube. However, there is not a permanent feature that loops on Youtube, only a temporary looping feature when you right click a video you are currently watching. I have tried another site such as the one below. Let me know if this InfiniteLooper link will work in place of a Youtube link:

http://www.infinitelooper.com/?v=xSsrL5kYK7I

**Comment by halfempty** [comment]
@gehalber Since we have GIFs now, do we still need this one?

**Comment by gehalber** [comment]
No.
