### ISSUE TITLE
Media Library

### ISSUE THREAD

**Issue by gehalber** [everythingtype/jsa#9]
Is there any way to organize the Media Library? They may want to have subcategories... Is that easily done?

**Comment by devinsays** [comment]
Media doesn't have a taxonomy by default. Generally media items are usually attached to a post/project/page that does have a taxonomy though, and that's generally how they would be referenced through code to display them on the front end.

There are a number of plugins that would allow a taxonomy to be added directly to media, but I'd be curious to know the use-cases you're considering before implementing.

**Comment by gehalber** [comment]
Ok. I’ll ask them.

**Comment by gehalber** [comment]
Here is there response:
I'm imagining that the breakdown could parallel the website structure at it's broadest breakdown, i.e. separate media folders for:
Projects & Research
About (to include all sections, e.g. profile, publications,etc.)
News

**Comment by devinsays** [comment]
Okay, but why would that be useful to them? Are they thinking of the website as a remote filesystem where they can save files and find documents? Something like box.com or dropbox.com would be much better suited to that...

**Comment by gehalber** [comment]
They’re architects. Just like to control everything.
Let me know if this is going to add a bunch of work to the project. If so, I’ll talk them out of it.

**Comment by devinsays** [comment]
I'm happy to look for a solution- just trying to figure out what exactly what they're trying to solve for. Generally clients don't even click on the "Media" menu item. Easiest solution might be to hide that menu. ;)

This plugin allows for a more flexible file system:
https://wordpress.org/plugins/custom-upload-dir

This plugin allows for media taxonomies:
https://wordpress.org/plugins/attachment-taxonomy-support
