### ISSUE TITLE
Backend fields

### ISSUE THREAD

**Issue by halfempty** [everythingtype/jsa#91]
Confirm all backend fields have been replicated on Live site

**Comment by gehalber** [comment]
Do you think you can do this today? I just want to give JSA a heads up. Thanks!

**Comment by halfempty** [comment]
@gehalber yes

**Comment by halfempty** [comment]
@gehalber Okay, I believe these are all mirrored

**Comment by gehalber** [comment]
Is the related to and from in?

**Comment by halfempty** [comment]
@gehalber It'll be part of the update.

**Comment by gehalber** [comment]
So they can’t make those changes in the backend now?
But they can add an image to info diptych in each project?

Could you tell me which backend items will have to wait until the update happens?

**Comment by halfempty** [comment]
@gehalber I can make that change if they're in there now and ready for it. 

I *think* everything else is in.

**Comment by gehalber** [comment]
Ok. That’d be great. If you make this change while they’re in there, will it affect the content at all? Or should I tell them to stop what they’re doing?
