### ISSUE TITLE
Responsive: Arrow color

### ISSUE THREAD

**Issue by halfempty** [everythingtype/jsa#95]
> not sure why arrow turns black when clicked, can it stay gray
> I think its fine as is. what about you?

**Comment by halfempty** [comment]
@gehalber It's black 'cause it has "focus", which is the touch-analogue for mouseover. I can make it grey or leave it black. I don't have a strong feeling either way. What would you prefer?

**Comment by halfempty** [comment]
@gehalber Would you like me to do something about this one? Or leave it as is?

**Comment by gehalber** [comment]
Let's remove the black in the arrows.

**Comment by halfempty** [comment]
Done
