### ISSUE TITLE
Responsive: Image load time

### ISSUE THREAD

**Issue by halfempty** [everythingtype/jsa#96]
> images take a very long time to load
> anything you can do about this?

**Comment by halfempty** [comment]
@gehalber Well, you know, the image loading times actually seem okay to me via my phone (I'm on T-mobile).

There ARE things we can do, but the result is that the images will look less good. What do you think?

**Comment by gehalber** [comment]
let me gauge Josh on this.
Its working ok for me too.

**Comment by gehalber** [comment]
Question: Is the full resolution of the image (~2000px) loading in mobile, or are the images in mobile loading according to screen size?

**Comment by halfempty** [comment]
@gehalber They're set to load the appropriate size for mobile

**Comment by gehalber** [comment]
Cool.
