### ISSUE TITLE
Responsive: Diptych advancing

### ISSUE THREAD

**Issue by halfempty** [everythingtype/jsa#99]
> tapping to advance skips over 2nd double image - needs to be fixed. can doubles stay as side-by-side doubles? or if you think they should be stacked (as they currently are) can tapping advance from double image #1 to double image #2 before going to the next slide?

> if its easy I think we should just remove that function on tablet.

**Comment by halfempty** [comment]
@gehalber If we do #97 (Responsive: Remove slide tap-to-advance) this one be moot

**Comment by gehalber** [comment]
ok. let’s do #97 as long its simple.
